name: FastAPI CI/CD Pipeline

# Trigger the workflow when a pull request is made to the dev branch
on:
  pull_request:
    branches:
      - dev

jobs:
  # Test Job
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies from the requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the unit tests (assuming they are in tests_main.py)
      - name: Run unit tests
        run: |
          pytest tests_main.py

  # Build Job (Only if tests pass)
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Check out the code again
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build and push Docker image to Docker Hub (if you have a Dockerfile)
      - name: Build and push Docker image
        run: |
          docker build -t bugrataskinyalcin/usecase-airpollution-backend .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push mydockerhubuser/usecase-airpollution-backend
